apiVersion: v1
kind: ConfigMap  # Create a config map
metadata:
  name: synergychat-api-configmap  # Name of object
data:  # Data to store in config map
  API_PORT: "8080"  # Store value 8080 under key "API_PORT"