apiVersion: v1
kind: ConfigMap  # Create a config map
metadata:
  name: synergychat-crawler-configmap  # Name of object
data:  # Data to store in config map
  CRAWLER_PORT: "8080"  # Store value 8080 under key "CRAWLER_PORT"
  CRAWLER_KEYWORDS: "love,hate,joy,sadness,anger,disgust,fear,surprise"